language: go

go:
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
      # HINT: this is only for interest -- decision to support new versions is made manually

before_install:
  - go get -t -v ./...
  - go get github.com/pierrre/gotestcover

script:
  # do regular coverage
  - gotestcover -v -covermode=count -coverprofile=coverage.intrapackage.txt ./...
  # do coverage for all packages and tests in `it` package
  - go test -covermode=count -coverprofile=coverage.it.txt -coverpkg=./... ./it
  # HINT: report merging is done by codecov.io script

after_success:
  # submit to codecov.io
  - bash <(curl -s https://codecov.io/bash)
